config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  resources :notes
  resource :user, only: [:new, :create, :show]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  get 'logout', to: "sessions#destroy"
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    
    def login?
        if current_user.nil?
            redirect_to login_path, alert: "You have to log in."
        end
    end
    def already_login?
        unless current_user.nil?
            redirect_to user_path, notice: "You are already logged in."
        end

    end

    def current_user
        if session[:user_id]
            current_user ||= User.find(session[:user_id])
        end

    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:subject, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only:[:edit, :update, :destroy]

    def index
        @posts = Post.all
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)

        if @post.save
            redirect_to posts_path
        else
            render :new
        end
    end

    def edit
    end

    def destroy
        @post.destroy
        redirect_to posts_path
    end

    def update
        if @post.update(post_params)
            redirect_to posts_path
        else
            render :edit
        end
    end

    private
    def post_params
        params.require(:post).permit(:title, :content)
    end

    def set_post
        @post = Post.find(params[:id])
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_login?, except: :destroy
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path, notice: "You hve successfully loggend in."
    else
      flash.now[:alert] = "Email or Password is invalid..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have successfully logged out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_login?, only: [:new, :create]
  before_action :login?, only: :show
  def new
    @user = User.new
  end

  def create
    user = User.new(users_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path, notice: "You have succesfully signed in."
    else
      render :new 
    end
  end

  def show
  end

  private
  def users_params
    params.require(:user).permit(:email, :password, :password_confimation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>Hello!</h1>
<%= link_to "Sign up", new_user_path %>
<%= link_to "Login", login_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= notice %>
    <%= alert %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :subject, style: "display: block" %>
    <%= form.text_field :subject %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>">
  <p>
    <strong>Subject:</strong>
    <%= note.subject %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= note.content %>
  </p>

</div>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Show this note", @note %> |
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notes</h1>

<div id="notes">
  <% @notes.each do |note| %>
    <%= render note %>
    <p>
      <%= link_to "Show this note", note %>
    </p>
  <% end %>
</div>

<%= link_to "New note", new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @note %>

<div>
  <%= link_to "Edit this note", edit_note_path(@note) %> |
  <%= link_to "Back to notes", notes_path %>

  <%= button_to "Destroy this note", @note, method: :delete %>
</div>

app/views/posts/edit.html.erb
<h1>投稿を編集します</h1>

<%= form_with model: @post, html:{class: "form-container"} do |f| %>
<div class="form-input">
    <%= f.label  :title %><%= f.text_field :title %>
</div>
<div class="form-input">
    <%= f.label :content %><%= f.text_area :content %>
</div>
<div class="button-container">
    <%= f.submit "更新する", class: "link-button" %>
</div>

<% end %>

app/views/posts/index.html.erb
<h1>投稿一覧です</h1>

<div class="button_container"><%= link_to "投稿する", new_post_path %></div>
<ul>
<% @posts.each do |p| %>
<h2><%= p.title %></h2>
<p><%= p.content %></p>
<span><small><%= p.created_at %></small></span>
<div class="edit-delete-wrapper">
<%= link_to "編集", edit_post_path(p), class: "link-button" %>
<%= button_to "削除", post_path(p), method: :delete, class: "link-delete-button" %>
</div>
<% end %>
</ul>

app/views/posts/new.html.erb
<h1>新しい投稿</h1>

<%= form_with model: @post, html:{class: "form-container"} do |f| %>
<div class="form-input">
    <%= f.label  :title %><%= f.text_field :title %>
</div>
<div class="form-input">
    <%= f.label :content %><%= f.text_area :content %>
</div>
<div class="button-container">
    <%= f.submit "投稿する", class: "link-button" %>
</div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with model: @user, url: user_path, local: true do |f| %>
    <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>
    <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>
    <div>
        <%= f.submit "sign up" %>
    </div>
    <%= link_to "Login", login_path %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome</h1>

<p>You are logged in as <strong><%= current_user.email %></strong></p>
<%= link_to "Logout", logout_path %>